[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.4.2
    adafruit/Adafruit BME280 Library @ ^2.3.0
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    links2004/WebSockets @ ^2.6.1
